# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_app', '0002_user_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmToken',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
